"""
Rewrites Notebook A and Notebook B to use MobileCLIP2-S4.

Notebook A changes:
  - Model: mobileclip_s2 -> MobileCLIP2-S4
  - Weights: loaded from attached Kaggle dataset /kaggle/input/mobileclip2-s4-weights/
  - Batch size: 64 -> 32

Notebook B changes:
  - Runs locally (not on Kaggle)
  - Loads indices from local kaggle_output/ directory
  - Loads MobileCLIP2-S4 from local models/MobileCLIP2-S4/MobileCLIP2_S4.pt
  - Removes Kaggle-specific imports (kaggle_secrets)
  - Loads Gemini API key from local .env file
"""

import json
from pathlib import Path

# ---------------------------------------------------------------------------
# NOTEBOOK A — GPU Indexing (runs on Kaggle T4x2 with MobileCLIP2-S4)
# ---------------------------------------------------------------------------

notebook_a = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# AIC 2026 — Kaggle Notebook A: GPU Preprocessing & Indexing\n",
                "\n",
                "**Purpose**: Batch-encode keyframes using **MobileCLIP2-S4** on Kaggle T4x2 GPUs, build FAISS vector indices, and build BM25 raw text indices. Output artifacts are saved to `/kaggle/working/` to be attached as an input dataset for **Notebook B (Search)**.\n",
                "\n",
                "**Model weights**: Attach the `mobileclip2-s4-weights` Kaggle dataset (containing `MobileCLIP2_S4.pt`) as an input to this notebook.\n",
                "\n",
                "**Execution mode**: Committed run (\"Save & Run All\") with GPU accelerator (T4x2)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Environment Setup & Package Installation\n",
                "!pip install -q open_clip_torch faiss-gpu rank_bm25 tqdm pillow pandas numpy"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2: Imports and Constants\n",
                "import os\n",
                "import glob\n",
                "import json\n",
                "import time\n",
                "import pickle\n",
                "from pathlib import Path\n",
                "from concurrent.futures import ThreadPoolExecutor, as_completed\n",
                "\n",
                "import torch\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "from PIL import Image\n",
                "from tqdm.auto import tqdm\n",
                "import faiss\n",
                "from rank_bm25 import BM25Okapi\n",
                "import open_clip\n",
                "\n",
                "# Hardcoded paths — confirmed working. Update if you re-upload under a different username/slug.\n",
                "DATASET_ROOT = Path(\"/kaggle/input/datasets/justavnesedude/aic2026-preprocessed-data\")\n",
                "if not DATASET_ROOT.exists():\n",
                "    # Fallback: recursive search\n",
                "    _found = glob.glob(\"/kaggle/input/**/keyframe_csvs\", recursive=True)\n",
                "    if _found:\n",
                "        DATASET_ROOT = Path(_found[0]).parent\n",
                "    else:\n",
                "        DATASET_ROOT = Path(\"./kaggle_dataset_staging\")  # local testing\n",
                "\n",
                "OUTPUT_DIR = Path(\"/kaggle/working\")\n",
                "CHECKPOINT_DIR = OUTPUT_DIR / \"checkpoints\"\n",
                "CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)\n",
                "\n",
                "# MobileCLIP2-S4 weights — confirmed Kaggle path\n",
                "MODEL_NAME = \"MobileCLIP2-S4\"\n",
                "MODEL_WEIGHTS_PATH = \"/kaggle/input/models/justavnesedude/mobileclip2-s4/pytorch/default/1/mobileclip2_s4.pt\"\n",
                "if not Path(MODEL_WEIGHTS_PATH).exists():\n",
                "    # Fallback: recursive search for any .pt file\n",
                "    _pt = glob.glob(\"/kaggle/input/**/*.pt\", recursive=True)\n",
                "    if _pt:\n",
                "        MODEL_WEIGHTS_PATH = _pt[0]\n",
                "        print(f\"Model found via fallback: {MODEL_WEIGHTS_PATH}\")\n",
                "    else:\n",
                "        raise FileNotFoundError(\"MobileCLIP2_S4.pt not found. Attach the model to this notebook.\")\n",
                "\n",
                "# Reduced to 32 (from 64) for MobileCLIP2-S4 VRAM safety on T4\n",
                "BATCH_SIZE = 32\n",
                "CHECKPOINT_INTERVAL = 20  # Save checkpoint every N videos\n",
                "\n",
                "print(f\"Using DATASET_ROOT: {DATASET_ROOT}\")\n",
                "print(f\"Using OUTPUT_DIR: {OUTPUT_DIR}\")\n",
                "print(f\"Using MODEL: {MODEL_NAME} from {MODEL_WEIGHTS_PATH}\")\n",
                "print(f\"PyTorch CUDA Available: {torch.cuda.is_available()}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"GPU Count: {torch.cuda.device_count()}\")\n",
                "    for i in range(torch.cuda.device_count()):\n",
                "        print(f\"  cuda:{i} -> {torch.cuda.get_device_name(i)}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: Metadata Assembly & Validation\n",
                "print(\"Loading keyframe metadata CSVs...\")\n",
                "csv_files = sorted(glob.glob(str(DATASET_ROOT / \"keyframe_csvs\" / \"*.csv\")))\n",
                "if not csv_files:\n",
                "    csv_files = sorted(glob.glob(str(DATASET_ROOT / \"**\" / \"keyframe_csvs\" / \"*.csv\"), recursive=True))\n",
                "\n",
                "print(f\"Found {len(csv_files)} keyframe CSV files.\")\n",
                "\n",
                "meta_rows = []\n",
                "dropped_count = 0\n",
                "total_count = 0\n",
                "\n",
                "for csv_path in csv_files:\n",
                "    video_name = Path(csv_path).stem\n",
                "    df_kf = pd.read_csv(csv_path)\n",
                "\n",
                "    for _, row in df_kf.iterrows():\n",
                "        total_count += 1\n",
                "        img_name = f\"{int(row['n']):04d}.jpg\"\n",
                "        img_path = DATASET_ROOT / \"keyframe_images\" / video_name / img_name\n",
                "        if not img_path.exists():\n",
                "            alt_paths = list(DATASET_ROOT.rglob(f\"*/{video_name}/{img_name}\"))\n",
                "            if alt_paths:\n",
                "                img_path = alt_paths[0]\n",
                "            else:\n",
                "                dropped_count += 1\n",
                "                continue\n",
                "\n",
                "        meta_rows.append({\n",
                "            \"video_name\": video_name,\n",
                "            \"n\": int(row['n']),\n",
                "            \"pts_time\": float(row['pts_time']),\n",
                "            \"fps\": float(row['fps']),\n",
                "            \"frame_idx\": int(row['frame_idx']),\n",
                "            \"image_path\": str(img_path)\n",
                "        })\n",
                "\n",
                "df_metadata = pd.DataFrame(meta_rows)\n",
                "print(f\"Metadata assembly complete: {len(df_metadata)} valid keyframes.\")\n",
                "print(f\"Dropped keyframes (missing files): {dropped_count} / {total_count} ({dropped_count/max(1,total_count):.2%})\")\n",
                "\n",
                "with open(OUTPUT_DIR / \"metadata_df.pkl\", \"wb\") as f:\n",
                "    pickle.dump(df_metadata, f)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Dual-GPU MobileCLIP2-S4 Visual Encoding\n",
                "def encode_batch_gpu(model, preprocess, image_paths, device):\n",
                "    images = []\n",
                "    valid_indices = []\n",
                "    for idx, p in enumerate(image_paths):\n",
                "        try:\n",
                "            img = Image.open(p).convert(\"RGB\")\n",
                "            tensor = preprocess(img)\n",
                "            images.append(tensor)\n",
                "            valid_indices.append(idx)\n",
                "        except Exception:\n",
                "            pass\n",
                "    if not images:\n",
                "        return np.zeros((0, 512), dtype=np.float32), valid_indices\n",
                "\n",
                "    batch = torch.stack(images).to(device)\n",
                "    with torch.no_grad():\n",
                "        feats = model.encode_image(batch)\n",
                "        feats /= feats.norm(dim=-1, keepdim=True)\n",
                "    return feats.cpu().numpy().astype(np.float32), valid_indices\n",
                "\n",
                "\n",
                "def worker_gpu_encode(gpu_id, chunk_df, model_name, weights_path):\n",
                "    device = torch.device(f\"cuda:{gpu_id}\" if torch.cuda.is_available() else \"cpu\")\n",
                "    # Load MobileCLIP2-S4 from local .pt file — call model.eval() for BatchNorm layers\n",
                "    model, _, preprocess = open_clip.create_model_and_transforms(model_name, pretrained=weights_path)\n",
                "    model = model.to(device).eval()\n",
                "\n",
                "    embeddings = []\n",
                "    paths = chunk_df[\"image_path\"].tolist()\n",
                "\n",
                "    for i in range(0, len(paths), BATCH_SIZE):\n",
                "        batch_paths = paths[i:i+BATCH_SIZE]\n",
                "        feats, _ = encode_batch_gpu(model, preprocess, batch_paths, device)\n",
                "        embeddings.append(feats)\n",
                "\n",
                "    if embeddings:\n",
                "        return np.vstack(embeddings)\n",
                "    return np.zeros((0, 512), dtype=np.float32)\n",
                "\n",
                "\n",
                "# Checkpoint recovery\n",
                "vis_emb_path = OUTPUT_DIR / \"visual_embeddings.npy\"\n",
                "if vis_emb_path.exists():\n",
                "    print(\"Loading existing visual_embeddings.npy from checkpoint...\")\n",
                "    visual_embeddings = np.load(vis_emb_path)\n",
                "else:\n",
                "    n_gpus = torch.cuda.device_count() if torch.cuda.is_available() else 1\n",
                "    print(f\"Starting MobileCLIP2-S4 encoding across {n_gpus} worker(s)...\")\n",
                "\n",
                "    chunks = np.array_split(df_metadata, n_gpus)\n",
                "    start_t = time.time()\n",
                "\n",
                "    if n_gpus > 1:\n",
                "        with ThreadPoolExecutor(max_workers=n_gpus) as executor:\n",
                "            futures = [executor.submit(worker_gpu_encode, i, chunks[i], MODEL_NAME, MODEL_WEIGHTS_PATH) for i in range(n_gpus)]\n",
                "            results = [f.result() for f in futures]\n",
                "        visual_embeddings = np.vstack(results)\n",
                "    else:\n",
                "        visual_embeddings = worker_gpu_encode(0, df_metadata, MODEL_NAME, MODEL_WEIGHTS_PATH)\n",
                "\n",
                "    print(f\"Encoding finished in {time.time() - start_t:.1f}s. Shape: {visual_embeddings.shape}\")\n",
                "    np.save(vis_emb_path, visual_embeddings)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5: Build FAISS Visual Index\n",
                "print(\"Building FAISS visual vector index (IndexFlatIP)...\")\n",
                "dim = visual_embeddings.shape[1]\n",
                "visual_index = faiss.IndexFlatIP(dim)\n",
                "visual_index.add(visual_embeddings)\n",
                "\n",
                "faiss_path = OUTPUT_DIR / \"visual_faiss.index\"\n",
                "faiss.write_index(visual_index, str(faiss_path))\n",
                "print(f\"Saved visual FAISS index: {visual_index.ntotal} vectors -> {faiss_path}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 6: Caption & Subtitle Text Feature Encoding (MobileCLIP2-S4 Text Encoder)\n",
                "print(\"Loading captions & subtitles for text embeddings...\")\n",
                "text_documents = []\n",
                "\n",
                "for idx, row in df_metadata.iterrows():\n",
                "    v_name = row['video_name']\n",
                "    pts = row['pts_time']\n",
                "\n",
                "    sub_text = \"\"\n",
                "    cap_text = \"\"\n",
                "\n",
                "    # Quick path checks instead of slow rglob\n",
                "    sub_file = DATASET_ROOT / \"subtitles\" / f\"{v_name}.json\"\n",
                "    if not sub_file.exists():\n",
                "        sub_file = DATASET_ROOT / \"L26_V100-V399\" / \"subtitles\" / f\"{v_name}.json\" # Fallback structure\n",
                "    \n",
                "    if sub_file.exists():\n",
                "        try:\n",
                "            with open(sub_file, \"r\", encoding=\"utf-8\") as f:\n",
                "                subs = json.load(f)\n",
                "                sub_text = \" \".join([s['text'] for s in subs if s['start'] <= pts <= s['end']])\n",
                "        except Exception:\n",
                "            pass\n",
                "\n",
                "    cap_file = DATASET_ROOT / \"captions\" / f\"{v_name}.json\"\n",
                "    if not cap_file.exists():\n",
                "        cap_file = DATASET_ROOT / \"L26_V100-V399\" / \"captions\" / f\"{v_name}.json\"\n",
                "\n",
                "    if cap_file.exists():\n",
                "        try:\n",
                "            with open(cap_file, \"r\", encoding=\"utf-8\") as f:\n",
                "                caps = json.load(f)\n",
                "                for c in caps:\n",
                "                    if c['start_time'] <= pts <= c['end_time']:\n",
                "                        cap_text = c['caption']\n",
                "                        break\n",
                "        except Exception:\n",
                "            pass\n",
                "\n",
                "    combined = f\"{sub_text} {cap_text}\".strip()\n",
                "    text_documents.append(combined if combined else \"video scene\")\n",
                "\n",
                "print(f\"Encoding {len(text_documents)} text documents with MobileCLIP2-S4 text encoder...\")\n",
                "device = torch.device(\"cuda:0\" if torch.cuda.is_available() else \"cpu\")\n",
                "model, _, _ = open_clip.create_model_and_transforms(MODEL_NAME, pretrained=MODEL_WEIGHTS_PATH)\n",
                "tokenizer = open_clip.get_tokenizer(MODEL_NAME)\n",
                "model = model.to(device).eval()\n",
                "\n",
                "text_embeddings_list = []\n",
                "with torch.no_grad():\n",
                "    for i in tqdm(range(0, len(text_documents), BATCH_SIZE), desc=\"Text Encoding\"):\n",
                "        batch_texts = text_documents[i:i+BATCH_SIZE]\n",
                "        tokens = tokenizer(batch_texts).to(device)\n",
                "        feats = model.encode_text(tokens)\n",
                "        feats /= feats.norm(dim=-1, keepdim=True)\n",
                "        text_embeddings_list.append(feats.cpu().numpy().astype(np.float32))\n",
                "\n",
                "text_embeddings = np.vstack(text_embeddings_list)\n",
                "np.save(OUTPUT_DIR / \"text_embeddings.npy\", text_embeddings)\n",
                "\n",
                "text_index = faiss.IndexFlatIP(dim)\n",
                "text_index.add(text_embeddings)\n",
                "faiss.write_index(text_index, str(OUTPUT_DIR / \"text_faiss.index\"))\n",
                "print(f\"Saved text FAISS index: {text_index.ntotal} vectors\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 7: Build BM25 Raw Text Corpus & Index\n",
                "print(\"Building BM25 corpus (subtitles + captions + object detections)...\")\n",
                "bm25_corpus = []\n",
                "\n",
                "for idx, row in df_metadata.iterrows():\n",
                "    v_name = row['video_name']\n",
                "    frame_idx = row['frame_idx']\n",
                "    pts = row['pts_time']\n",
                "\n",
                "    obj_text = \"\"\n",
                "    # Direct checks instead of rglob\n",
                "    obj_paths = [\n",
                "        DATASET_ROOT / \"objects\" / v_name / f\"{frame_idx:03d}.json\",\n",
                "        DATASET_ROOT / \"objects\" / v_name / f\"{row['n']:04d}.json\",\n",
                "        DATASET_ROOT / \"L26_V100-V399\" / \"objects\" / v_name / f\"{frame_idx:03d}.json\",\n",
                "    ]\n",
                "    for opath in obj_paths:\n",
                "        if opath.exists():\n",
                "            try:\n",
                "                with open(opath, \"r\", encoding=\"utf-8\") as f:\n",
                "                    o_data = json.load(f)\n",
                "                    labels = o_data.get(\"detection_class_entities\", [])\n",
                "                    obj_text = \" \".join(labels)\n",
                "            except Exception:\n",
                "                pass\n",
                "            break\n",
                "\n",
                "    doc_str = f\"{text_documents[idx]} {obj_text}\".strip()\n",
                "    tokens = doc_str.lower().split()\n",
                "    bm25_corpus.append(tokens if tokens else [\"scene\"])\n",
                "\n",
                "print(f\"Fitting BM25Okapi on {len(bm25_corpus)} documents...\")\n",
                "bm25 = BM25Okapi(bm25_corpus)\n",
                "\n",
                "with open(OUTPUT_DIR / \"bm25_corpus.pkl\", \"wb\") as f:\n",
                "    pickle.dump({\"bm25\": bm25, \"corpus\": bm25_corpus}, f)\n",
                "\n",
                "print(\"BM25 index saved successfully.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 8: Output Summary & Integrity Verification\n",
                "print(\"=\"*60)\n",
                "print(\"PREPROCESSING COMPLETE — ARTIFACT SUMMARY:\")\n",
                "print(\"=\"*60)\n",
                "artifacts = [\n",
                "    \"metadata_df.pkl\",\n",
                "    \"visual_embeddings.npy\",\n",
                "    \"visual_faiss.index\",\n",
                "    \"text_embeddings.npy\",\n",
                "    \"text_faiss.index\",\n",
                "    \"bm25_corpus.pkl\"\n",
                "]\n",
                "for art in artifacts:\n",
                "    p = OUTPUT_DIR / art\n",
                "    if p.exists():\n",
                "        size_mb = p.stat().st_size / (1024*1024)\n",
                "        print(f\"  [OK] {art:25s} -> {size_mb:8.2f} MB\")\n",
                "    else:\n",
                "        print(f\"  [MISSING] {art:25s}\")\n",
                "print(\"=\"*60)\n",
                "print()\n",
                "print(\"NEXT STEP: Download all 6 files above, put them in kaggle_output/\")\n",
                "print(\"in your local project, then run Notebook B locally.\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# ---------------------------------------------------------------------------
# NOTEBOOK B — Local Search (runs on local CPU, loads indices from kaggle_output/)
# ---------------------------------------------------------------------------

notebook_b = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# AIC 2026 — Notebook B: Interactive Search, Clipping & VQA (LOCAL)\n",
                "\n",
                "**Purpose**: Loads the pre-built FAISS and BM25 indices generated by **Notebook A on Kaggle**, performs multimodal event retrieval (KIS, VKIS, TRAKE), applies Unified Clipping with Reciprocal Rank Fusion (RRF), and answers questions via Gemini Flash VQA.\n",
                "\n",
                "**Execution mode**: Local CPU. Runs interactively in Jupyter or as a Python script.\n",
                "\n",
                "**Prerequisites**:\n",
                "1. Download all 6 output files from Notebook A on Kaggle and place them in `kaggle_output/`.\n",
                "2. Download `MobileCLIP2_S4.pt` and place it at `models/MobileCLIP2-S4/MobileCLIP2_S4.pt`.\n",
                "3. Ensure your `.env` file contains `GEMINI_API_KEY_1=AIzaSy...` for VQA."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Package Installation\n",
                "# Run once. Use the project virtual environment:\n",
                "#   .venv\\Scripts\\pip install open_clip_torch faiss-cpu rank_bm25 google-generativeai matplotlib pillow pandas numpy python-dotenv\n",
                "# NOTE: faiss-cpu (not faiss-gpu) for local CPU-only usage"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2: Imports & Path Configuration\n",
                "import os\n",
                "import json\n",
                "import pickle\n",
                "from pathlib import Path\n",
                "\n",
                "import torch\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "from PIL import Image\n",
                "import faiss\n",
                "from rank_bm25 import BM25Okapi\n",
                "import open_clip\n",
                "import google.generativeai as genai\n",
                "from dotenv import load_dotenv\n",
                "\n",
                "# ── Paths ────────────────────────────────────────────────────────────────────\n",
                "PROJECT_ROOT = Path(\".\")  # Assumes notebook is run from the AIHCM project root\n",
                "\n",
                "# Indices downloaded from Kaggle Notebook A output\n",
                "INDEX_DIR = PROJECT_ROOT / \"kaggle_output\"\n",
                "\n",
                "# Local MobileCLIP2-S4 weights for query encoding\n",
                "MODEL_WEIGHTS_PATH = PROJECT_ROOT / \"models\" / \"MobileCLIP2-S4\" / \"MobileCLIP2_S4.pt\"\n",
                "MODEL_NAME = \"MobileCLIP2-S4\"\n",
                "\n",
                "# Keyframe images (used for display)\n",
                "KEYFRAMES_DIR = PROJECT_ROOT / \"DAKE_output\" / \"extracted_keyframe_images\"\n",
                "\n",
                "assert INDEX_DIR.exists(), f\"kaggle_output/ not found. Download Notebook A outputs first.\"\n",
                "assert MODEL_WEIGHTS_PATH.exists(), f\"Model not found at {MODEL_WEIGHTS_PATH}\"\n",
                "\n",
                "print(f\"Loading indices from: {INDEX_DIR}\")\n",
                "print(f\"Using model: {MODEL_NAME} from {MODEL_WEIGHTS_PATH}\")\n",
                "\n",
                "# ── Gemini API for VQA — loaded from local .env ───────────────────────────\n",
                "load_dotenv(PROJECT_ROOT / \".env\")\n",
                "GEMINI_AVAILABLE = False\n",
                "try:\n",
                "    gemini_key = (\n",
                "        os.getenv(\"GEMINI_API_KEY_1\")\n",
                "        or os.getenv(\"GEMINI_API_KEY\")\n",
                "    )\n",
                "    if gemini_key:\n",
                "        genai.configure(api_key=gemini_key)\n",
                "        vqa_model = genai.GenerativeModel(\"gemini-2.0-flash\")\n",
                "        GEMINI_AVAILABLE = True\n",
                "        print(\"Gemini API successfully configured for VQA!\")\n",
                "    else:\n",
                "        print(\"Notice: No GEMINI_API_KEY found in .env. VQA will be disabled.\")\n",
                "except Exception as e:\n",
                "    print(f\"Notice: Gemini API setup failed ({e}). VQA disabled.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: Load Pre-built Indices & MobileCLIP2-S4 Query Encoder\n",
                "print(\"Loading metadata...\")\n",
                "with open(INDEX_DIR / \"metadata_df.pkl\", \"rb\") as f:\n",
                "    df_metadata = pickle.load(f)\n",
                "print(f\"Loaded {len(df_metadata)} keyframe records.\")\n",
                "\n",
                "print(\"Loading FAISS indices...\")\n",
                "visual_index = faiss.read_index(str(INDEX_DIR / \"visual_faiss.index\"))\n",
                "text_index   = faiss.read_index(str(INDEX_DIR / \"text_faiss.index\"))\n",
                "\n",
                "print(\"Loading BM25 corpus...\")\n",
                "with open(INDEX_DIR / \"bm25_corpus.pkl\", \"rb\") as f:\n",
                "    bm25_data = pickle.load(f)\n",
                "    bm25 = bm25_data[\"bm25\"]\n",
                "    bm25_corpus = bm25_data[\"corpus\"]\n",
                "\n",
                "# Load MobileCLIP2-S4 for query encoding — CPU only\n",
                "device = torch.device(\"cpu\")\n",
                "print(f\"Loading MobileCLIP2-S4 query encoder on {device}...\")\n",
                "clip_model, _, _ = open_clip.create_model_and_transforms(\n",
                "    MODEL_NAME, pretrained=str(MODEL_WEIGHTS_PATH)\n",
                ")\n",
                "tokenizer = open_clip.get_tokenizer(MODEL_NAME)\n",
                "clip_model = clip_model.to(device).eval()  # .eval() important for BatchNorm layers\n",
                "\n",
                "print(\"All indices and query encoder loaded successfully!\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Single Modality Search Functions\n",
                "def encode_query_text(query_text):\n",
                "    tokens = tokenizer([query_text]).to(device)\n",
                "    with torch.no_grad():\n",
                "        feats = clip_model.encode_text(tokens)\n",
                "        feats /= feats.norm(dim=-1, keepdim=True)\n",
                "    return feats.cpu().numpy().astype(np.float32)\n",
                "\n",
                "def encode_query_image(image_path):\n",
                "    _, _, preprocess = open_clip.create_model_and_transforms(MODEL_NAME, pretrained=str(MODEL_WEIGHTS_PATH))\n",
                "    img = Image.open(image_path).convert(\"RGB\")\n",
                "    tensor = preprocess(img).unsqueeze(0).to(device)\n",
                "    with torch.no_grad():\n",
                "        feats = clip_model.encode_image(tensor)\n",
                "        feats /= feats.norm(dim=-1, keepdim=True)\n",
                "    return feats.cpu().numpy().astype(np.float32)\n",
                "\n",
                "\n",
                "def search_visual(query_text=None, query_image_path=None, top_k=100):\n",
                "    if query_image_path:\n",
                "        q_emb = encode_query_image(query_image_path)\n",
                "    elif query_text:\n",
                "        q_emb = encode_query_text(query_text)\n",
                "    else:\n",
                "        raise ValueError(\"Must provide text or image query for visual search.\")\n",
                "    scores, indices = visual_index.search(q_emb, top_k)\n",
                "    results = []\n",
                "    for idx, sc in zip(indices[0], scores[0]):\n",
                "        if idx < len(df_metadata):\n",
                "            row = df_metadata.iloc[idx].to_dict()\n",
                "            row['score'] = float(sc)\n",
                "            row['source'] = 'visual'\n",
                "            results.append(row)\n",
                "    return results\n",
                "\n",
                "\n",
                "def search_text_emb(query_text, top_k=100):\n",
                "    q_emb = encode_query_text(query_text)\n",
                "    scores, indices = text_index.search(q_emb, top_k)\n",
                "    results = []\n",
                "    for idx, sc in zip(indices[0], scores[0]):\n",
                "        if idx < len(df_metadata):\n",
                "            row = df_metadata.iloc[idx].to_dict()\n",
                "            row['score'] = float(sc)\n",
                "            row['source'] = 'text_emb'\n",
                "            results.append(row)\n",
                "    return results\n",
                "\n",
                "\n",
                "def search_bm25(query_text, top_k=100):\n",
                "    tokens = query_text.lower().split()\n",
                "    scores = bm25.get_scores(tokens)\n",
                "    top_indices = np.argsort(-scores)[:top_k]\n",
                "    results = []\n",
                "    for idx in top_indices:\n",
                "        if scores[idx] > 0 and idx < len(df_metadata):\n",
                "            row = df_metadata.iloc[idx].to_dict()\n",
                "            row['score'] = float(scores[idx])\n",
                "            row['source'] = 'bm25'\n",
                "            results.append(row)\n",
                "    return results"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5: Score Fusion Engine (RRF & Weighted Fallback)\n",
                "def reciprocal_rank_fusion(results_lists, k=60):\n",
                "    \"\"\"Scale-free RRF algorithm: score(doc) = sum(1 / (k + rank))\"\"\"\n",
                "    rrf_scores = {}\n",
                "    item_map = {}\n",
                "\n",
                "    for res_list in results_lists:\n",
                "        for rank, item in enumerate(res_list):\n",
                "            key = f\"{item['video_name']}_{item['frame_idx']}\"\n",
                "            if key not in item_map:\n",
                "                item_map[key] = item\n",
                "                rrf_scores[key] = 0.0\n",
                "            rrf_scores[key] += 1.0 / (k + rank + 1)\n",
                "\n",
                "    sorted_keys = sorted(rrf_scores.keys(), key=lambda x: rrf_scores[x], reverse=True)\n",
                "    fused = []\n",
                "    for k_val in sorted_keys:\n",
                "        item = item_map[k_val].copy()\n",
                "        item['score'] = rrf_scores[k_val]\n",
                "        item['fusion_method'] = 'RRF'\n",
                "        fused.append(item)\n",
                "    return fused\n",
                "\n",
                "\n",
                "def weighted_fusion(results_lists, weights=(0.4, 0.3, 0.3)):\n",
                "    \"\"\"Fallback weighted sum with min-max normalization per list\"\"\"\n",
                "    weighted_scores = {}\n",
                "    item_map = {}\n",
                "\n",
                "    for idx, res_list in enumerate(results_lists):\n",
                "        w = weights[idx]\n",
                "        if not res_list:\n",
                "            continue\n",
                "        scores = [it['score'] for it in res_list]\n",
                "        min_s, max_s = min(scores), max(scores)\n",
                "        denom = max_s - min_s if max_s > min_s else 1.0\n",
                "\n",
                "        for item in res_list:\n",
                "            key = f\"{item['video_name']}_{item['frame_idx']}\"\n",
                "            if key not in item_map:\n",
                "                item_map[key] = item\n",
                "                weighted_scores[key] = 0.0\n",
                "            norm_score = (item['score'] - min_s) / denom\n",
                "            weighted_scores[key] += w * norm_score\n",
                "\n",
                "    sorted_keys = sorted(weighted_scores.keys(), key=lambda x: weighted_scores[x], reverse=True)\n",
                "    fused = []\n",
                "    for k_val in sorted_keys:\n",
                "        item = item_map[k_val].copy()\n",
                "        item['score'] = weighted_scores[k_val]\n",
                "        item['fusion_method'] = 'Weighted'\n",
                "        fused.append(item)\n",
                "    return fused\n",
                "\n",
                "\n",
                "def retrieve_all(query_text=None, query_image_path=None, top_k=100, mode=\"rrf\"):\n",
                "    results = []\n",
                "    if query_text or query_image_path:\n",
                "        results.append(search_visual(query_text, query_image_path, top_k))\n",
                "    if query_text:\n",
                "        results.append(search_text_emb(query_text, top_k))\n",
                "        results.append(search_bm25(query_text, top_k))\n",
                "\n",
                "    if mode == \"rrf\":\n",
                "        return reciprocal_rank_fusion(results)\n",
                "    else:\n",
                "        return weighted_fusion(results)\n",
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 6: Unified Clipping Algorithm (Two-pointer + NMS)\n",
                "def unified_clipping(candidate_frames, max_clip_duration=20.0, top_k_clips=20, nms_threshold=0.5):\n",
                "    \"\"\"\n",
                "    Linear two-pointer sliding window sweep over frame candidates grouped by video.\n",
                "    Ranked by highest frame score. Applies NMS to eliminate duplicate overlapping windows.\n",
                "    \"\"\"\n",
                "    by_video = {}\n",
                "    for f in candidate_frames:\n",
                "        v = f['video_name']\n",
                "        if v not in by_video:\n",
                "            by_video[v] = []\n",
                "        by_video[v].append(f)\n",
                "\n",
                "    clips = []\n",
                "    for v_name, frames in by_video.items():\n",
                "        frames = sorted(frames, key=lambda x: x['pts_time'])\n",
                "        n = len(frames)\n",
                "        left = 0\n",
                "        for right in range(n):\n",
                "            while frames[right]['pts_time'] - frames[left]['pts_time'] > max_clip_duration:\n",
                "                left += 1\n",
                "            window = frames[left:right+1]\n",
                "            best_frame = max(window, key=lambda x: x['score'])\n",
                "            clips.append({\n",
                "                \"video_name\": v_name,\n",
                "                \"start_time\": window[0]['pts_time'],\n",
                "                \"end_time\": window[-1]['pts_time'],\n",
                "                \"duration\": window[-1]['pts_time'] - window[0]['pts_time'],\n",
                "                \"best_frame\": best_frame,\n",
                "                \"score\": best_frame['score'],\n",
                "                \"n_frames\": len(window)\n",
                "            })\n",
                "\n",
                "    clips = sorted(clips, key=lambda x: x['score'], reverse=True)\n",
                "\n",
                "    # NMS Deduplication\n",
                "    selected_clips = []\n",
                "    for c in clips:\n",
                "        overlap = False\n",
                "        for sel in selected_clips:\n",
                "            if sel['video_name'] == c['video_name']:\n",
                "                inter_start = max(sel['start_time'], c['start_time'])\n",
                "                inter_end   = min(sel['end_time'],   c['end_time'])\n",
                "                if inter_end > inter_start:\n",
                "                    inter_dur = inter_end - inter_start\n",
                "                    union_dur = (sel['end_time'] - sel['start_time']) + (c['end_time'] - c['start_time']) - inter_dur\n",
                "                    if inter_dur / max(1e-5, union_dur) > nms_threshold:\n",
                "                        overlap = True\n",
                "                        break\n",
                "        if not overlap:\n",
                "            selected_clips.append(c)\n",
                "            if len(selected_clips) >= top_k_clips:\n",
                "                break\n",
                "\n",
                "    return selected_clips"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 7: Gemini Flash VQA Integration\n",
                "def answer_vqa(image_path, question_text):\n",
                "    if not GEMINI_AVAILABLE:\n",
                "        return \"Gemini API key not configured. Cannot perform VQA.\"\n",
                "    try:\n",
                "        img = Image.open(image_path)\n",
                "        prompt = f\"Hãy trả lời câu hỏi sau một cách ngắn gọn, chính xác bằng tiếng Việt dựa vào hình ảnh này:\\nCâu hỏi: {question_text}\"\n",
                "        response = vqa_model.generate_content([img, prompt])\n",
                "        return response.text.strip()\n",
                "    except Exception as e:\n",
                "        return f\"VQA Error: {e}\""
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 8: Result Visualization Engine\n",
                "def show_results(clips, max_display=10, cols=5):\n",
                "    display_clips = clips[:max_display]\n",
                "    if not display_clips:\n",
                "        print(\"No matching clips found.\")\n",
                "        return\n",
                "\n",
                "    rows = (len(display_clips) + cols - 1) // cols\n",
                "    fig, axes = plt.subplots(rows, cols, figsize=(cols * 4, rows * 3.5))\n",
                "    if rows == 1 and cols == 1:\n",
                "        axes = np.array([[axes]])\n",
                "    elif rows == 1 or cols == 1:\n",
                "        axes = np.atleast_2d(axes)\n",
                "\n",
                "    for idx, c in enumerate(display_clips):\n",
                "        r, col = idx // cols, idx % cols\n",
                "        ax = axes[r, col]\n",
                "        bf = c['best_frame']\n",
                "\n",
                "        # Try the path stored in metadata first; fall back to local keyframes dir\n",
                "        img_p = Path(bf['image_path'])\n",
                "        if not img_p.exists():\n",
                "            img_p = KEYFRAMES_DIR / bf['video_name'] / f\"{bf['n']:04d}.jpg\"\n",
                "\n",
                "        if img_p.exists():\n",
                "            ax.imshow(Image.open(img_p))\n",
                "        else:\n",
                "            ax.text(0.5, 0.5, \"Image Missing\", ha='center', va='center')\n",
                "\n",
                "        title = f\"#{idx+1}: {c['video_name']}\\n{c['start_time']:.1f}s-{c['end_time']:.1f}s | Score: {c['score']:.4f}\"\n",
                "        ax.set_title(title, fontsize=9)\n",
                "        ax.axis('off')\n",
                "\n",
                "    for i in range(idx + 1, rows * cols):\n",
                "        r, col = i // cols, i % cols\n",
                "        axes[r, col].axis('off')\n",
                "\n",
                "    plt.tight_layout()\n",
                "    plt.show()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 9: Interactive KIS Search Demo\n",
                "query = \"con tôm hấp sốt mayonnaise\"\n",
                "print(f\"Executing search for query: '{query}'...\")\n",
                "\n",
                "raw_candidates = retrieve_all(query, top_k=50, mode=\"rrf\")\n",
                "top_clips = unified_clipping(raw_candidates, max_clip_duration=20.0, top_k_clips=10)\n",
                "\n",
                "print(f\"Found {len(top_clips)} video event clips after unified clipping and NMS:\")\n",
                "show_results(top_clips)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 10: TRAKE Temporal Search & VQA Demo\n",
                "print(\"=== TRAKE Multi-Query Temporal Alignment Demo ===\")\n",
                "multi_queries = [\n",
                "    \"chuẩn bị nguyên liệu tôm\",\n",
                "    \"hấp tôm trên nồi\",\n",
                "    \"món ăn hoàn thành bày ra đĩa\"\n",
                "]\n",
                "\n",
                "trake_results = []\n",
                "for q_idx, q in enumerate(multi_queries):\n",
                "    cands = retrieve_all(q, top_k=30, mode=\"rrf\")\n",
                "    for c in cands:\n",
                "        c['query_idx'] = q_idx\n",
                "    trake_results.extend(cands)\n",
                "\n",
                "trake_clips = unified_clipping(trake_results, max_clip_duration=60.0, top_k_clips=5)\n",
                "show_results(trake_clips)\n",
                "\n",
                "if trake_clips and GEMINI_AVAILABLE:\n",
                "    top_frame = trake_clips[0]['best_frame']['image_path']\n",
                "    question = \"Trong hình có những món ăn nào?\"\n",
                "    answer = answer_vqa(top_frame, question)\n",
                "    print(f\"\\n[VQA Demo] Question: {question}\")\n",
                "    print(f\"[VQA Demo] Answer: {answer}\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write both notebooks
out_a = Path("kaggle_notebook_a_preprocessing.ipynb")
out_b = Path("kaggle_notebook_b_search.ipynb")

with open(out_a, "w", encoding="utf-8") as f:
    json.dump(notebook_a, f, ensure_ascii=False, indent=1)
print(f"Written: {out_a}")

with open(out_b, "w", encoding="utf-8") as f:
    json.dump(notebook_b, f, ensure_ascii=False, indent=1)
print(f"Written: {out_b}")

# Create the required output directory
Path("kaggle_output").mkdir(exist_ok=True)
print("Created: kaggle_output/")

print("\nDone! Summary of changes:")
print("  Notebook A  -> Uses MobileCLIP2-S4 from Kaggle dataset 'mobileclip2-s4-weights'")
print("               -> BATCH_SIZE reduced to 32")
print("  Notebook B  -> Runs locally (no Kaggle imports)")
print("               -> Loads indices from kaggle_output/")
print("               -> Loads MobileCLIP2-S4 from models/MobileCLIP2-S4/MobileCLIP2_S4.pt")
print("               -> Gemini API key from local .env file")
